# Generated by Django 4.0.9 on 2023-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_word_lastoccurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneshotClues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue1', models.CharField(max_length=5)),
                ('clue2', models.CharField(max_length=5)),
                ('clue3', models.CharField(max_length=5)),
                ('clue4', models.CharField(max_length=5)),
                ('clue5', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
