# Generated by Django 4.0.9 on 2023-04-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_oneshotclues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneshotclues',
            options={'verbose_name': 'Clue', 'verbose_name_plural': 'Clues'},
        ),
        migrations.AlterModelOptions(
            name='oneshotword',
            options={'verbose_name': 'Daily Word', 'verbose_name_plural': 'Daily Words'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
    ]
