# Generated by Django 4.0.9 on 2023-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_oneshotclues_options_alter_oneshotword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordle_attempt',
            options={'verbose_name': 'Word Attempt', 'verbose_name_plural': 'Word Attempts'},
        ),
        migrations.AddField(
            model_name='wordle_attempt',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
