# Generated by Django 4.0.9 on 2023-05-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_wordle_attempt_guess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneshotword',
            options={'verbose_name': 'Oneshot Daily Word', 'verbose_name_plural': 'Oneshot Daily Words'},
        ),
        migrations.AddField(
            model_name='oneshotword',
            name='clues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.oneshotclues'),
            preserve_default=False,
        ),
    ]
