# Generated by Django 4.0.9 on 2025-06-25 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('number', models.CharField(max_length=5, unique=True)),
                ('clue1', models.CharField(blank=True, max_length=5, null=True)),
                ('clue2', models.CharField(blank=True, max_length=5, null=True)),
                ('clue3', models.CharField(blank=True, max_length=5, null=True)),
                ('clue4', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Daily One-Shot Cows and Bulls',
                'verbose_name_plural': 'Daily One-Shot Cows and Bulls',
            },
        ),
        migrations.CreateModel(
            name='DailyOCBAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=5)),
                ('score', models.IntegerField(default=0)),
                ('ocb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cows_bulls.dailyocb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily One-Shot Cows and Bulls Attempt',
                'verbose_name_plural': 'Daily One-Shot Cows and Bulls Attempts',
                'unique_together': {('user', 'ocb')},
            },
        ),
    ]
