# Generated by Django 4.0.9 on 2025-06-25 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cows_bulls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyocbattempt',
            options={'ordering': ['timestamp'], 'verbose_name': 'Daily One-Shot Cows and Bulls Attempt', 'verbose_name_plural': 'Daily One-Shot Cows and Bulls Attempts'},
        ),
        migrations.RenameField(
            model_name='dailyocbattempt',
            old_name='score',
            new_name='bulls',
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='cows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
