# Generated by Django 4.0.9 on 2025-06-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cows_bulls', '0002_alter_dailyocbattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyocbattempt',
            options={'ordering': ['timestamp'], 'verbose_name': 'Daily Cows and Bulls Attempt', 'verbose_name_plural': 'Daily Cows and Bulls Attempts'},
        ),
        migrations.AlterUniqueTogether(
            name='dailyocbattempt',
            unique_together=set(),
        ),
    ]
