# Generated by Django 4.0.9 on 2023-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supporter',
            field=models.BooleanField(default=False),
        ),
    ]
