# Generated by Django 4.0.9 on 2023-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colourMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='colourTone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
