# Generated by Django 4.0.9 on 2023-05-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_colourmode_user_colourtone_user_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_ads',
            field=models.BooleanField(default=False),
        ),
    ]
