# Generated by Django 4.0.9 on 2025-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_no_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalTanglePointsEver',
            field=models.IntegerField(default=0),
        ),
    ]
