# Generated by Django 4.0.9 on 2025-06-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_totaltanglepointsever'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cows_bulls_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cows_bulls_points',
            field=models.IntegerField(default=0),
        ),
    ]
