# Generated by Django 6.0 on 2026-02-01 20:48

import oneshot_guessle.c_cipher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_cipher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer_flags',
            field=models.JSONField(blank=True, default=oneshot_guessle.c_cipher.models.default_answer_flags),
        ),
    ]
