# Generated by Django 6.0 on 2026-02-01 21:08

import oneshot_guessle.c_cipher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_cipher', '0002_puzzle_answer_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='success_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer_flags',
            field=models.JSONField(blank=True, default=oneshot_guessle.c_cipher.models.default_answer_flags, help_text='Answer normalization flags. Available: trim, lowercase, collapse_spaces, strip_all_spaces. Example: ["trim", "lowercase"]'),
        ),
    ]
