# Generated by Django 6.0 on 2026-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_cipher', '0003_puzzle_success_message_alter_puzzle_answer_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='hijri_year',
            field=models.PositiveSmallIntegerField(db_index=True, default=1447),
            preserve_default=False,
        ),
    ]
