# Generated by Django 6.0.2 on 2026-02-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_cipher', '0004_puzzle_hijri_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.TextField(blank=True),
        ),
    ]
