# Generated by Django 4.0.9 on 2023-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dayscorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='daysincorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.png', help_text='Choose your avatar', null=True, upload_to='images/profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='misseddays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
