# Generated by Django 4.0.9 on 2023-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dayscorrect_user_daysincorrect_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highestStreak',
            field=models.IntegerField(default=0),
        ),
    ]
