# Generated by Django 4.0.9 on 2025-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ks', models.CharField(max_length=3)),
                ('week_tests_analysis', models.CharField(max_length=50)),
                ('weekly_tests', models.CharField(max_length=50)),
                ('mocks_analysis', models.CharField(max_length=50)),
                ('mocks', models.CharField(max_length=50)),
            ],
        ),
    ]
