# Generated by Django 4.2.27 on 2025-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_sheetstab"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetstab",
            name="json_workbook",
            field=models.URLField(blank=True, default=dict),
        ),
    ]
