# Generated by Django 6.0 on 2025-12-22 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_sheetstab_json_workbook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
