# Generated by Django 6.0.3 on 2026-06-13 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMorph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_number', models.PositiveIntegerField(blank=True, help_text='Override the displayed puzzle number. Leave blank to use the database ID.', null=True, unique=True)),
                ('start_word', models.CharField(max_length=5)),
                ('end_word', models.CharField(max_length=5)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('least_morphs', models.PositiveIntegerField(default=0)),
                ('most_morphs', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Word Morph Daily Word',
                'verbose_name_plural': 'Word Morph Daily Words',
            },
        ),
        migrations.CreateModel(
            name='Morph_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.JSONField(default=list)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('morph_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordmorph.wordmorph')),
            ],
            options={
                'verbose_name': 'Word Morph Attempt',
                'verbose_name_plural': 'Word Morph Attempts',
            },
        ),
    ]
