version: '3'

volumes:
  oneshot_guessle_local_postgres_data: {}
  oneshot_guessle_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: oneshot_guessle_local_django
    container_name: oneshot_guessle_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000 --noreload #/start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: oneshot_guessle_production_postgres
    container_name: oneshot_guessle_local_postgres
    volumes:
      - oneshot_guessle_local_postgres_data:/var/lib/postgresql/data
      - oneshot_guessle_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: oneshot_guessle_local_docs
  #   container_name: oneshot_guessle_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./oneshot_guessle:/app/oneshot_guessle:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
