# Generated by Django 4.0.9 on 2023-05-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guessle_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Word Attempt',
                'verbose_name_plural': 'Word Attempts',
            },
        ),
        migrations.CreateModel(
            name='OneshotClues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue1', models.CharField(max_length=5)),
                ('clue2', models.CharField(max_length=5)),
                ('clue3', models.CharField(max_length=5)),
                ('clue4', models.CharField(max_length=5)),
                ('clue5', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clue',
                'verbose_name_plural': 'Clues',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('frequency', models.PositiveBigIntegerField(default=0)),
                ('lastOccurance', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='OneshotWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correctAnswers', models.PositiveIntegerField(default=0)),
                ('clues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.oneshotclues')),
            ],
            options={
                'verbose_name': 'Oneshot Daily Word',
                'verbose_name_plural': 'Oneshot Daily Words',
            },
        ),
    ]
