# Generated by Django 4.0.9 on 2023-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='frequency',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='lastOccurance',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
