# Generated by Django 4.0.9 on 2023-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_word_frequency_word_lastoccurance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yetle',
            new_name='OneshotWord',
        ),
        migrations.AlterField(
            model_name='word',
            name='lastOccurance',
            field=models.DateTimeField(),
        ),
    ]
