# Generated by Django 4.0.9 on 2023-05-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_oneshotclueseasy_oneshotwordeasy_easyguessle_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=6)),
                ('frequency', models.PositiveBigIntegerField(default=0)),
                ('lastOccurance', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Hard Word',
                'verbose_name_plural': 'Hard Words',
            },
        ),
        migrations.AlterModelOptions(
            name='easyguessle_attempt',
            options={'verbose_name': 'Easy Word Attempt', 'verbose_name_plural': 'Easy Words Attempts'},
        ),
        migrations.CreateModel(
            name='HardGuessle_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.oneshotword')),
            ],
            options={
                'verbose_name': 'Hard Word Attempt',
                'verbose_name_plural': 'Hard Words Attempts',
            },
        ),
    ]
