# Generated by Django 4.0.9 on 2023-05-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_oneshotwordeasy_clues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyguessle_attempt',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.oneshotwordeasy'),
        ),
    ]
