# Generated by Django 4.0.9 on 2023-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_oneshotclueshard_oneshotwordhard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='proper_noun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wordshard',
            name='proper_noun',
            field=models.BooleanField(default=True),
        ),
    ]
