# Generated by Django 4.2.27 on 2025-12-07 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_word_proper_noun_wordshard_proper_noun"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="easyguessle_attempt",
            options={
                "verbose_name": "Easy Guessle Word Attempt",
                "verbose_name_plural": "Easy Guessle Words Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="guessle_attempt",
            options={
                "verbose_name": "Regular Guessle Word Attempt",
                "verbose_name_plural": "Regular Guessle Word Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="hardguessle_attempt",
            options={
                "verbose_name": "Hard Guessle Word Attempt",
                "verbose_name_plural": "Hard Guessle Words Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="oneshotclues",
            options={
                "verbose_name": "Oneshot Regular Clue",
                "verbose_name_plural": "Oneshot Regular Clues",
            },
        ),
        migrations.AlterModelOptions(
            name="oneshotclueseasy",
            options={
                "verbose_name": "Oneshot Easy Clue",
                "verbose_name_plural": "OneshotEasy Clues",
            },
        ),
        migrations.AlterModelOptions(
            name="oneshotclueshard",
            options={
                "verbose_name": "Oneshot Hard Clue",
                "verbose_name_plural": "Oneshot Hard Clues",
            },
        ),
        migrations.AlterModelOptions(
            name="oneshotword",
            options={
                "verbose_name": "Oneshot Regular Daily Word",
                "verbose_name_plural": "Oneshot Regular Daily Words",
            },
        ),
        migrations.AlterModelOptions(
            name="word",
            options={
                "verbose_name": "5 Letter Word",
                "verbose_name_plural": "5 Letter Words",
            },
        ),
        migrations.AlterModelOptions(
            name="wordshard",
            options={
                "verbose_name": "6 letter Word (Hard)",
                "verbose_name_plural": "6 letter Words (Hard)",
            },
        ),
    ]
