# Generated by Django 4.0.9 on 2023-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_guessle_attempt_options_guessle_attempt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessle_attempt',
            name='guess',
            field=models.CharField(default='roast', max_length=5),
            preserve_default=False,
        ),
    ]
