# Generated by Django 6.0.3 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_easyguessle_attempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneshotword',
            name='puzzle_number',
            field=models.PositiveIntegerField(blank=True, help_text='Override the displayed puzzle number. Leave blank to use the database ID.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='oneshotwordeasy',
            name='puzzle_number',
            field=models.PositiveIntegerField(blank=True, help_text='Override the displayed puzzle number. Leave blank to use the database ID.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='oneshotwordhard',
            name='puzzle_number',
            field=models.PositiveIntegerField(blank=True, help_text='Override the displayed puzzle number. Leave blank to use the database ID.', null=True, unique=True),
        ),
    ]
