# Generated by Django 4.0.9 on 2024-07-28 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keystage', models.CharField(choices=[('ks3', 'KS5'), ('ks4', 'KS4'), ('ks5', 'KS5')], max_length=20)),
                ('exam_board', models.CharField(choices=[('ocr', 'OCR'), ('aqa', 'AQA')], max_length=20)),
                ('category', models.CharField(choices=[('ks3', 'KS5'), ('ks4', 'KS4'), ('ks5', 'KS5')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_resources.resource')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
