# Generated by Django 4.0.9 on 2024-07-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
    ]
