# Generated by Django 4.0.9 on 2024-07-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_resources', '0002_remove_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='keystage',
            field=models.CharField(choices=[('ks3', 'KS3'), ('ks4', 'KS4'), ('ks5', 'KS5')], max_length=20),
        ),
    ]
