# Generated by Django 6.0.3 on 2026-07-09 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulls', '0003_alter_dailyocbattempt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyocbattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Daily Cows and Bulls Attempt', 'verbose_name_plural': 'Daily Cows and Bulls Attempts'},
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='attempts',
            field=models.JSONField(default=list, help_text='Array of {guess, cows, bulls, attempt_number}'),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='solved_on_attempt',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailyocbattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='dailyocbattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='dailyocbattempt',
            name='bulls',
        ),
        migrations.RemoveField(
            model_name='dailyocbattempt',
            name='cows',
        ),
        migrations.RemoveField(
            model_name='dailyocbattempt',
            name='guess',
        ),
    ]
