# Generated by Django 6.0.3 on 2026-07-09 16:39

from django.db import migrations
from django.db.models import Max, F
from collections import defaultdict


def migrate_attempts_forward(apps, schema_editor):
    """
    Migrate old attempt records to new JSON format.
    Groups all attempts by (user, ocb) into a single record, deletes duplicates.
    """
    DailyOCBAttempt = apps.get_model('bulls', 'DailyOCBAttempt')
    
    # Get all old records
    old_records = DailyOCBAttempt.objects.all().order_by('timestamp')
    
    # Group by (user_id, ocb_id)
    attempts_by_user_ocb = {}
    
    for record in old_records:
        key = (record.user_id, record.ocb_id)
        
        if key not in attempts_by_user_ocb:
            # First record for this user-puzzle combo
            attempts_by_user_ocb[key] = {
                'record': record,
                'attempts': [],
            }
    
    # Now populate attempts arrays and consolidate
    all_records = DailyOCBAttempt.objects.all().order_by('timestamp')
    for record in all_records:
        key = (record.user_id, record.ocb_id)
        info = attempts_by_user_ocb[key]
        
        # Add this attempt to the array
        if hasattr(record, 'guess') and record.guess:  # Make sure it has old schema fields
            info['attempts'].append({
                'guess': record.guess,
                'cows': record.cows if hasattr(record, 'cows') else 0,
                'bulls': record.bulls if hasattr(record, 'bulls') else 0,
                'attempt_number': len(info['attempts']) + 1,
            })
            
            # Update solved status on first attempt with bulls == 5
            if not info.get('is_solved') and record.bulls == 5:
                info['is_solved'] = True
                info['solved_on_attempt'] = len(info['attempts'])
                info['points_awarded'] = record.points_awarded
    
    # Update consolidated records
    records_to_delete = []
    for (user_id, ocb_id), info in attempts_by_user_ocb.items():
        main_record = info['record']
        main_record.attempts = info['attempts']
        main_record.is_solved = info.get('is_solved', False)
        main_record.solved_on_attempt = info.get('solved_on_attempt', None)
        main_record.points_awarded = info.get('points_awarded', 0)
        main_record.save(update_fields=['attempts', 'is_solved', 'solved_on_attempt', 'points_awarded'])
    
    # Delete all duplicate records (keeping only the first one per user-puzzle combo)
    seen_keys = set()
    for record in all_records:
        key = (record.user_id, record.ocb_id)
        if key not in seen_keys:
            seen_keys.add(key)
        else:
            record.delete()


def migrate_attempts_backward(apps, schema_editor):
    """
    Reverse migration - would need to recreate individual records from JSON
    but this is complex, so we'll just warn
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bulls', '0004_alter_dailyocbattempt_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_attempts_forward, migrate_attempts_backward),
        migrations.AlterUniqueTogether(
            name='dailyocbattempt',
            unique_together={('user', 'ocb')},
        ),
    ]
