# Generated by Django 6.0.3 on 2026-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulls', '0005_migrate_attempts_to_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyocb',
            options={'ordering': ['-challenge_number'], 'verbose_name': 'Daily One-Shot Cows and Bulls', 'verbose_name_plural': 'Daily One-Shot Cows and Bulls'},
        ),
        migrations.AddField(
            model_name='dailyocb',
            name='challenge_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
