# Generated by Django 6.0.3 on 2026-07-09 17:26

from django.db import migrations


def populate_challenge_numbers(apps, schema_editor):
    """Populate challenge_number with sequential numbers based on date order"""
    DailyOCB = apps.get_model('bulls', 'DailyOCB')
    
    # Get all puzzles ordered by date (oldest first)
    puzzles = DailyOCB.objects.all().order_by('date')
    
    # Assign sequential challenge numbers starting from 1
    for idx, puzzle in enumerate(puzzles, start=1):
        puzzle.challenge_number = idx
        puzzle.save(update_fields=['challenge_number'])


def reverse_populate(apps, schema_editor):
    """Reset challenge_number to None"""
    DailyOCB = apps.get_model('bulls', 'DailyOCB')
    DailyOCB.objects.all().update(challenge_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bulls', '0006_alter_dailyocb_options_dailyocb_challenge_number'),
    ]

    operations = [
        migrations.RunPython(populate_challenge_numbers, reverse_populate),
    ]
