# Generated by Django 4.0.9 on 2025-06-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=12)),
                ('word2', models.CharField(max_length=12)),
                ('word3', models.CharField(max_length=12)),
                ('word4', models.CharField(max_length=12)),
                ('word5', models.CharField(max_length=12)),
                ('word6', models.CharField(max_length=12)),
                ('word7', models.CharField(max_length=12)),
                ('word8', models.CharField(max_length=12)),
                ('word9', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'verbose_name': 'Daily Tangle',
                'verbose_name_plural': 'Daily Tangles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TangleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangle.dailytangle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tangle Attempt',
                'verbose_name_plural': 'Tangle Attempts',
            },
        ),
    ]
