# Generated by Django 4.0.9 on 2025-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tangleattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tangle Attempt', 'verbose_name_plural': 'Tangle Attempts'},
        ),
        migrations.RenameField(
            model_name='tangleattempt',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tangleattempt',
            name='attempt',
        ),
        migrations.AddField(
            model_name='tangleattempt',
            name='words',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
